apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trondelagfk-no
resources:
  - ../../../base2
patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-flyt-value-converting-service_trondelagfk-no"
      - op: replace
        path: "/metadata/labels/fintlabs.no~1org-id"
        value: "trondelagfk.no"
      - op: replace
        path: "/spec/url"
        value:
          hostname: "flyt.vigoiks.no"
          basePath: "/alpha/trondelagfk-no/api/intern/value-convertings"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "trondelag-no.flyt.*"
    target:
      kind: Application
      name: fint-flyt-value-converting-service

