apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trondelagfk-no
resources:
  - ../../../base2
commonLabels:
  app.kubernetes.io/name: fint-flyt-value-converting-service
  app.kubernetes.io/instance: fint-flyt-value-converting-service_trondelagfk-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-flyt
  fintlabs.no/team: flyt
  fintlabs.no/org-id: trondelagfk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/url"
        value:
          hostname: "flyt.vigoiks.no"
          basePath: "/alpha/trondelagfk-no/api/intern/value-convertings"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "trondelag-no.flyt.*"
    target:
      kind: Application
      name: fint-flyt-value-converting-service

