novari:
  kafka:
    topic:
      domain-context: flyt
    application-id: ${fint.application-id}
    tracing:
      enabled: true

spring:
  kafka:
    consumer:
      group-id: ${fint.application-id}
