apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-flyt-value-converting-service
spec:
  orgId: trondelagfk.no
  image: ghcr.io/fintlabs/fint-flyt-value-converting-service:latest
  kafka:
    enabled: true
    acls:
      - permission: admin
        topic: 'no-permission'
  database:
    enabled: true
  url:
    hostname: hostname
    basePath: path
  ingress:
    enabled: true
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx1840M'
