apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-flyt-value-converting-service
  labels:
    app.kubernetes.io/name: fint-flyt-value-converting-service
    app.kubernetes.io/instance: fint-flyt-value-converting-service_fintlabs-no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: fintlabs.no
spec:
  orgId: trondelagfk.no
  image: ghcr.io/fintlabs/fint-flyt-value-converting-service:latest
  kafka:
    enabled: true
    acls:
      - permission: admin
        topic: 'no-permission'
  database:
    enabled: true
  url:
    hostname: hostname
    basePath: path
  ingress:
    enabled: true
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx1840M'
